# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_rohc', [dirname(__file__)])
        except ImportError:
            import _rohc
            return _rohc
        if fp is not None:
            try:
                _mod = imp.load_module('_rohc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _rohc = swig_import_helper()
    del swig_import_helper
else:
    import _rohc
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


ROHC_PACKET_IR = _rohc.ROHC_PACKET_IR
ROHC_PACKET_IR_DYN = _rohc.ROHC_PACKET_IR_DYN
ROHC_PACKET_UO_0 = _rohc.ROHC_PACKET_UO_0
ROHC_PACKET_UO_1 = _rohc.ROHC_PACKET_UO_1
ROHC_PACKET_UO_1_ID = _rohc.ROHC_PACKET_UO_1_ID
ROHC_PACKET_UO_1_TS = _rohc.ROHC_PACKET_UO_1_TS
ROHC_PACKET_UO_1_RTP = _rohc.ROHC_PACKET_UO_1_RTP
ROHC_PACKET_UOR_2 = _rohc.ROHC_PACKET_UOR_2
ROHC_PACKET_UOR_2_RTP = _rohc.ROHC_PACKET_UOR_2_RTP
ROHC_PACKET_UOR_2_ID = _rohc.ROHC_PACKET_UOR_2_ID
ROHC_PACKET_UOR_2_TS = _rohc.ROHC_PACKET_UOR_2_TS
ROHC_PACKET_NORMAL = _rohc.ROHC_PACKET_NORMAL
ROHC_PACKET_UNKNOWN = _rohc.ROHC_PACKET_UNKNOWN
ROHC_PACKET_TCP_CO_COMMON = _rohc.ROHC_PACKET_TCP_CO_COMMON
ROHC_PACKET_TCP_RND_1 = _rohc.ROHC_PACKET_TCP_RND_1
ROHC_PACKET_TCP_RND_2 = _rohc.ROHC_PACKET_TCP_RND_2
ROHC_PACKET_TCP_RND_3 = _rohc.ROHC_PACKET_TCP_RND_3
ROHC_PACKET_TCP_RND_4 = _rohc.ROHC_PACKET_TCP_RND_4
ROHC_PACKET_TCP_RND_5 = _rohc.ROHC_PACKET_TCP_RND_5
ROHC_PACKET_TCP_RND_6 = _rohc.ROHC_PACKET_TCP_RND_6
ROHC_PACKET_TCP_RND_7 = _rohc.ROHC_PACKET_TCP_RND_7
ROHC_PACKET_TCP_RND_8 = _rohc.ROHC_PACKET_TCP_RND_8
ROHC_PACKET_TCP_SEQ_1 = _rohc.ROHC_PACKET_TCP_SEQ_1
ROHC_PACKET_TCP_SEQ_2 = _rohc.ROHC_PACKET_TCP_SEQ_2
ROHC_PACKET_TCP_SEQ_3 = _rohc.ROHC_PACKET_TCP_SEQ_3
ROHC_PACKET_TCP_SEQ_4 = _rohc.ROHC_PACKET_TCP_SEQ_4
ROHC_PACKET_TCP_SEQ_5 = _rohc.ROHC_PACKET_TCP_SEQ_5
ROHC_PACKET_TCP_SEQ_6 = _rohc.ROHC_PACKET_TCP_SEQ_6
ROHC_PACKET_TCP_SEQ_7 = _rohc.ROHC_PACKET_TCP_SEQ_7
ROHC_PACKET_TCP_SEQ_8 = _rohc.ROHC_PACKET_TCP_SEQ_8
ROHC_PACKET_MAX = _rohc.ROHC_PACKET_MAX
ROHC_EXT_0 = _rohc.ROHC_EXT_0
ROHC_EXT_1 = _rohc.ROHC_EXT_1
ROHC_EXT_2 = _rohc.ROHC_EXT_2
ROHC_EXT_3 = _rohc.ROHC_EXT_3
ROHC_EXT_NONE = _rohc.ROHC_EXT_NONE
ROHC_EXT_UNKNOWN = _rohc.ROHC_EXT_UNKNOWN

def rohc_get_packet_descr(*args):
  return _rohc.rohc_get_packet_descr(*args)
rohc_get_packet_descr = _rohc.rohc_get_packet_descr

def rohc_get_ext_descr(*args):
  return _rohc.rohc_get_ext_descr(*args)
rohc_get_ext_descr = _rohc.rohc_get_ext_descr
class rohc_ts(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, rohc_ts, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, rohc_ts, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sec"] = _rohc.rohc_ts_sec_set
    __swig_getmethods__["sec"] = _rohc.rohc_ts_sec_get
    if _newclass:sec = _swig_property(_rohc.rohc_ts_sec_get, _rohc.rohc_ts_sec_set)
    __swig_setmethods__["nsec"] = _rohc.rohc_ts_nsec_set
    __swig_getmethods__["nsec"] = _rohc.rohc_ts_nsec_get
    if _newclass:nsec = _swig_property(_rohc.rohc_ts_nsec_get, _rohc.rohc_ts_nsec_set)
    def __init__(self, *args): 
        this = _rohc.new_rohc_ts(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _rohc.delete_rohc_ts
    __del__ = lambda self : None;
rohc_ts_swigregister = _rohc.rohc_ts_swigregister
rohc_ts_swigregister(rohc_ts)

class rohc_buf(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, rohc_buf, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, rohc_buf, name)
    __repr__ = _swig_repr
    __swig_setmethods__["time"] = _rohc.rohc_buf_time_set
    __swig_getmethods__["time"] = _rohc.rohc_buf_time_get
    if _newclass:time = _swig_property(_rohc.rohc_buf_time_get, _rohc.rohc_buf_time_set)
    __swig_setmethods__["data"] = _rohc.rohc_buf_data_set
    __swig_getmethods__["data"] = _rohc.rohc_buf_data_get
    if _newclass:data = _swig_property(_rohc.rohc_buf_data_get, _rohc.rohc_buf_data_set)
    __swig_setmethods__["max_len"] = _rohc.rohc_buf_max_len_set
    __swig_getmethods__["max_len"] = _rohc.rohc_buf_max_len_get
    if _newclass:max_len = _swig_property(_rohc.rohc_buf_max_len_get, _rohc.rohc_buf_max_len_set)
    __swig_setmethods__["offset"] = _rohc.rohc_buf_offset_set
    __swig_getmethods__["offset"] = _rohc.rohc_buf_offset_get
    if _newclass:offset = _swig_property(_rohc.rohc_buf_offset_get, _rohc.rohc_buf_offset_set)
    __swig_setmethods__["len"] = _rohc.rohc_buf_len_set
    __swig_getmethods__["len"] = _rohc.rohc_buf_len_get
    if _newclass:len = _swig_property(_rohc.rohc_buf_len_get, _rohc.rohc_buf_len_set)
    def __init__(self, *args): 
        this = _rohc.new_rohc_buf(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _rohc.delete_rohc_buf
    __del__ = lambda self : None;
    def get(self, *args): return _rohc.rohc_buf_get(self, *args)
rohc_buf_swigregister = _rohc.rohc_buf_swigregister
rohc_buf_swigregister(rohc_buf)


def rohc_buf_is_malformed(*args):
  return _rohc.rohc_buf_is_malformed(*args)
rohc_buf_is_malformed = _rohc.rohc_buf_is_malformed

def rohc_buf_is_empty(*args):
  return _rohc.rohc_buf_is_empty(*args)
rohc_buf_is_empty = _rohc.rohc_buf_is_empty

def rohc_buf_pull(*args):
  return _rohc.rohc_buf_pull(*args)
rohc_buf_pull = _rohc.rohc_buf_pull

def rohc_buf_push(*args):
  return _rohc.rohc_buf_push(*args)
rohc_buf_push = _rohc.rohc_buf_push

def rohc_buf_avail_len(*args):
  return _rohc.rohc_buf_avail_len(*args)
rohc_buf_avail_len = _rohc.rohc_buf_avail_len

def rohc_buf_data_at(*args):
  return _rohc.rohc_buf_data_at(*args)
rohc_buf_data_at = _rohc.rohc_buf_data_at

def rohc_buf_data(*args):
  return _rohc.rohc_buf_data(*args)
rohc_buf_data = _rohc.rohc_buf_data

def rohc_buf_prepend(*args):
  return _rohc.rohc_buf_prepend(*args)
rohc_buf_prepend = _rohc.rohc_buf_prepend

def rohc_buf_append(*args):
  return _rohc.rohc_buf_append(*args)
rohc_buf_append = _rohc.rohc_buf_append

def rohc_buf_append_buf(*args):
  return _rohc.rohc_buf_append_buf(*args)
rohc_buf_append_buf = _rohc.rohc_buf_append_buf

def rohc_buf_reset(*args):
  return _rohc.rohc_buf_reset(*args)
rohc_buf_reset = _rohc.rohc_buf_reset
ROHC_ETHERTYPE = _rohc.ROHC_ETHERTYPE
ROHC_STATUS_OK = _rohc.ROHC_STATUS_OK
ROHC_STATUS_SEGMENT = _rohc.ROHC_STATUS_SEGMENT
ROHC_STATUS_MALFORMED = _rohc.ROHC_STATUS_MALFORMED
ROHC_STATUS_NO_CONTEXT = _rohc.ROHC_STATUS_NO_CONTEXT
ROHC_STATUS_BAD_CRC = _rohc.ROHC_STATUS_BAD_CRC
ROHC_STATUS_OUTPUT_TOO_SMALL = _rohc.ROHC_STATUS_OUTPUT_TOO_SMALL
ROHC_STATUS_ERROR = _rohc.ROHC_STATUS_ERROR
ROHC_UNKNOWN_MODE = _rohc.ROHC_UNKNOWN_MODE
ROHC_U_MODE = _rohc.ROHC_U_MODE
ROHC_O_MODE = _rohc.ROHC_O_MODE
ROHC_R_MODE = _rohc.ROHC_R_MODE
ROHC_LARGE_CID_MAX = _rohc.ROHC_LARGE_CID_MAX
ROHC_SMALL_CID_MAX = _rohc.ROHC_SMALL_CID_MAX
ROHC_LARGE_CID = _rohc.ROHC_LARGE_CID
ROHC_SMALL_CID = _rohc.ROHC_SMALL_CID
ROHC_PROFILE_UNCOMPRESSED = _rohc.ROHC_PROFILE_UNCOMPRESSED
ROHC_PROFILE_RTP = _rohc.ROHC_PROFILE_RTP
ROHC_PROFILE_UDP = _rohc.ROHC_PROFILE_UDP
ROHC_PROFILE_ESP = _rohc.ROHC_PROFILE_ESP
ROHC_PROFILE_IP = _rohc.ROHC_PROFILE_IP
ROHC_PROFILE_RTP_LLA = _rohc.ROHC_PROFILE_RTP_LLA
ROHC_PROFILE_TCP = _rohc.ROHC_PROFILE_TCP
ROHC_PROFILE_UDPLITE_RTP = _rohc.ROHC_PROFILE_UDPLITE_RTP
ROHC_PROFILE_UDPLITE = _rohc.ROHC_PROFILE_UDPLITE
ROHC_PROFILE_MAX = _rohc.ROHC_PROFILE_MAX

def rohc_version():
  return _rohc.rohc_version()
rohc_version = _rohc.rohc_version

def rohc_strerror(*args):
  return _rohc.rohc_strerror(*args)
rohc_strerror = _rohc.rohc_strerror

def rohc_get_mode_descr(*args):
  return _rohc.rohc_get_mode_descr(*args)
rohc_get_mode_descr = _rohc.rohc_get_mode_descr

def rohc_get_profile_descr(*args):
  return _rohc.rohc_get_profile_descr(*args)
rohc_get_profile_descr = _rohc.rohc_get_profile_descr
ROHC_PROFILE_GENERAL = _rohc.ROHC_PROFILE_GENERAL
ROHC_TRACE_DEBUG = _rohc.ROHC_TRACE_DEBUG
ROHC_TRACE_INFO = _rohc.ROHC_TRACE_INFO
ROHC_TRACE_WARNING = _rohc.ROHC_TRACE_WARNING
ROHC_TRACE_ERROR = _rohc.ROHC_TRACE_ERROR
ROHC_TRACE_LEVEL_MAX = _rohc.ROHC_TRACE_LEVEL_MAX
ROHC_TRACE_COMP = _rohc.ROHC_TRACE_COMP
ROHC_TRACE_DECOMP = _rohc.ROHC_TRACE_DECOMP
ROHC_TRACE_ENTITY_MAX = _rohc.ROHC_TRACE_ENTITY_MAX
ROHC_COMP_STATE_UNKNOWN = _rohc.ROHC_COMP_STATE_UNKNOWN
ROHC_COMP_STATE_IR = _rohc.ROHC_COMP_STATE_IR
ROHC_COMP_STATE_FO = _rohc.ROHC_COMP_STATE_FO
ROHC_COMP_STATE_SO = _rohc.ROHC_COMP_STATE_SO
class rohc_comp_last_packet_info2_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, rohc_comp_last_packet_info2_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, rohc_comp_last_packet_info2_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["version_major"] = _rohc.rohc_comp_last_packet_info2_t_version_major_set
    __swig_getmethods__["version_major"] = _rohc.rohc_comp_last_packet_info2_t_version_major_get
    if _newclass:version_major = _swig_property(_rohc.rohc_comp_last_packet_info2_t_version_major_get, _rohc.rohc_comp_last_packet_info2_t_version_major_set)
    __swig_setmethods__["version_minor"] = _rohc.rohc_comp_last_packet_info2_t_version_minor_set
    __swig_getmethods__["version_minor"] = _rohc.rohc_comp_last_packet_info2_t_version_minor_get
    if _newclass:version_minor = _swig_property(_rohc.rohc_comp_last_packet_info2_t_version_minor_get, _rohc.rohc_comp_last_packet_info2_t_version_minor_set)
    __swig_setmethods__["context_id"] = _rohc.rohc_comp_last_packet_info2_t_context_id_set
    __swig_getmethods__["context_id"] = _rohc.rohc_comp_last_packet_info2_t_context_id_get
    if _newclass:context_id = _swig_property(_rohc.rohc_comp_last_packet_info2_t_context_id_get, _rohc.rohc_comp_last_packet_info2_t_context_id_set)
    __swig_setmethods__["is_context_init"] = _rohc.rohc_comp_last_packet_info2_t_is_context_init_set
    __swig_getmethods__["is_context_init"] = _rohc.rohc_comp_last_packet_info2_t_is_context_init_get
    if _newclass:is_context_init = _swig_property(_rohc.rohc_comp_last_packet_info2_t_is_context_init_get, _rohc.rohc_comp_last_packet_info2_t_is_context_init_set)
    __swig_setmethods__["context_mode"] = _rohc.rohc_comp_last_packet_info2_t_context_mode_set
    __swig_getmethods__["context_mode"] = _rohc.rohc_comp_last_packet_info2_t_context_mode_get
    if _newclass:context_mode = _swig_property(_rohc.rohc_comp_last_packet_info2_t_context_mode_get, _rohc.rohc_comp_last_packet_info2_t_context_mode_set)
    __swig_setmethods__["context_state"] = _rohc.rohc_comp_last_packet_info2_t_context_state_set
    __swig_getmethods__["context_state"] = _rohc.rohc_comp_last_packet_info2_t_context_state_get
    if _newclass:context_state = _swig_property(_rohc.rohc_comp_last_packet_info2_t_context_state_get, _rohc.rohc_comp_last_packet_info2_t_context_state_set)
    __swig_setmethods__["context_used"] = _rohc.rohc_comp_last_packet_info2_t_context_used_set
    __swig_getmethods__["context_used"] = _rohc.rohc_comp_last_packet_info2_t_context_used_get
    if _newclass:context_used = _swig_property(_rohc.rohc_comp_last_packet_info2_t_context_used_get, _rohc.rohc_comp_last_packet_info2_t_context_used_set)
    __swig_setmethods__["profile_id"] = _rohc.rohc_comp_last_packet_info2_t_profile_id_set
    __swig_getmethods__["profile_id"] = _rohc.rohc_comp_last_packet_info2_t_profile_id_get
    if _newclass:profile_id = _swig_property(_rohc.rohc_comp_last_packet_info2_t_profile_id_get, _rohc.rohc_comp_last_packet_info2_t_profile_id_set)
    __swig_setmethods__["packet_type"] = _rohc.rohc_comp_last_packet_info2_t_packet_type_set
    __swig_getmethods__["packet_type"] = _rohc.rohc_comp_last_packet_info2_t_packet_type_get
    if _newclass:packet_type = _swig_property(_rohc.rohc_comp_last_packet_info2_t_packet_type_get, _rohc.rohc_comp_last_packet_info2_t_packet_type_set)
    __swig_setmethods__["total_last_uncomp_size"] = _rohc.rohc_comp_last_packet_info2_t_total_last_uncomp_size_set
    __swig_getmethods__["total_last_uncomp_size"] = _rohc.rohc_comp_last_packet_info2_t_total_last_uncomp_size_get
    if _newclass:total_last_uncomp_size = _swig_property(_rohc.rohc_comp_last_packet_info2_t_total_last_uncomp_size_get, _rohc.rohc_comp_last_packet_info2_t_total_last_uncomp_size_set)
    __swig_setmethods__["header_last_uncomp_size"] = _rohc.rohc_comp_last_packet_info2_t_header_last_uncomp_size_set
    __swig_getmethods__["header_last_uncomp_size"] = _rohc.rohc_comp_last_packet_info2_t_header_last_uncomp_size_get
    if _newclass:header_last_uncomp_size = _swig_property(_rohc.rohc_comp_last_packet_info2_t_header_last_uncomp_size_get, _rohc.rohc_comp_last_packet_info2_t_header_last_uncomp_size_set)
    __swig_setmethods__["total_last_comp_size"] = _rohc.rohc_comp_last_packet_info2_t_total_last_comp_size_set
    __swig_getmethods__["total_last_comp_size"] = _rohc.rohc_comp_last_packet_info2_t_total_last_comp_size_get
    if _newclass:total_last_comp_size = _swig_property(_rohc.rohc_comp_last_packet_info2_t_total_last_comp_size_get, _rohc.rohc_comp_last_packet_info2_t_total_last_comp_size_set)
    __swig_setmethods__["header_last_comp_size"] = _rohc.rohc_comp_last_packet_info2_t_header_last_comp_size_set
    __swig_getmethods__["header_last_comp_size"] = _rohc.rohc_comp_last_packet_info2_t_header_last_comp_size_get
    if _newclass:header_last_comp_size = _swig_property(_rohc.rohc_comp_last_packet_info2_t_header_last_comp_size_get, _rohc.rohc_comp_last_packet_info2_t_header_last_comp_size_set)
    def __init__(self): 
        this = _rohc.new_rohc_comp_last_packet_info2_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _rohc.delete_rohc_comp_last_packet_info2_t
    __del__ = lambda self : None;
rohc_comp_last_packet_info2_t_swigregister = _rohc.rohc_comp_last_packet_info2_t_swigregister
rohc_comp_last_packet_info2_t_swigregister(rohc_comp_last_packet_info2_t)

class rohc_comp_general_info_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, rohc_comp_general_info_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, rohc_comp_general_info_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["version_major"] = _rohc.rohc_comp_general_info_t_version_major_set
    __swig_getmethods__["version_major"] = _rohc.rohc_comp_general_info_t_version_major_get
    if _newclass:version_major = _swig_property(_rohc.rohc_comp_general_info_t_version_major_get, _rohc.rohc_comp_general_info_t_version_major_set)
    __swig_setmethods__["version_minor"] = _rohc.rohc_comp_general_info_t_version_minor_set
    __swig_getmethods__["version_minor"] = _rohc.rohc_comp_general_info_t_version_minor_get
    if _newclass:version_minor = _swig_property(_rohc.rohc_comp_general_info_t_version_minor_get, _rohc.rohc_comp_general_info_t_version_minor_set)
    __swig_setmethods__["contexts_nr"] = _rohc.rohc_comp_general_info_t_contexts_nr_set
    __swig_getmethods__["contexts_nr"] = _rohc.rohc_comp_general_info_t_contexts_nr_get
    if _newclass:contexts_nr = _swig_property(_rohc.rohc_comp_general_info_t_contexts_nr_get, _rohc.rohc_comp_general_info_t_contexts_nr_set)
    __swig_setmethods__["packets_nr"] = _rohc.rohc_comp_general_info_t_packets_nr_set
    __swig_getmethods__["packets_nr"] = _rohc.rohc_comp_general_info_t_packets_nr_get
    if _newclass:packets_nr = _swig_property(_rohc.rohc_comp_general_info_t_packets_nr_get, _rohc.rohc_comp_general_info_t_packets_nr_set)
    __swig_setmethods__["uncomp_bytes_nr"] = _rohc.rohc_comp_general_info_t_uncomp_bytes_nr_set
    __swig_getmethods__["uncomp_bytes_nr"] = _rohc.rohc_comp_general_info_t_uncomp_bytes_nr_get
    if _newclass:uncomp_bytes_nr = _swig_property(_rohc.rohc_comp_general_info_t_uncomp_bytes_nr_get, _rohc.rohc_comp_general_info_t_uncomp_bytes_nr_set)
    __swig_setmethods__["comp_bytes_nr"] = _rohc.rohc_comp_general_info_t_comp_bytes_nr_set
    __swig_getmethods__["comp_bytes_nr"] = _rohc.rohc_comp_general_info_t_comp_bytes_nr_get
    if _newclass:comp_bytes_nr = _swig_property(_rohc.rohc_comp_general_info_t_comp_bytes_nr_get, _rohc.rohc_comp_general_info_t_comp_bytes_nr_set)
    def __init__(self): 
        this = _rohc.new_rohc_comp_general_info_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _rohc.delete_rohc_comp_general_info_t
    __del__ = lambda self : None;
rohc_comp_general_info_t_swigregister = _rohc.rohc_comp_general_info_t_swigregister
rohc_comp_general_info_t_swigregister(rohc_comp_general_info_t)

ROHC_COMP_FEATURE_NONE = _rohc.ROHC_COMP_FEATURE_NONE
ROHC_COMP_FEATURE_COMPAT_1_6_x = _rohc.ROHC_COMP_FEATURE_COMPAT_1_6_x
ROHC_COMP_FEATURE_NO_IP_CHECKSUMS = _rohc.ROHC_COMP_FEATURE_NO_IP_CHECKSUMS

def rohc_comp_new2(*args):
  return _rohc.rohc_comp_new2(*args)
rohc_comp_new2 = _rohc.rohc_comp_new2

def rohc_comp_free(*args):
  return _rohc.rohc_comp_free(*args)
rohc_comp_free = _rohc.rohc_comp_free

def rohc_comp_set_traces_cb2(*args):
  return _rohc.rohc_comp_set_traces_cb2(*args)
rohc_comp_set_traces_cb2 = _rohc.rohc_comp_set_traces_cb2

def rohc_compress4(*args):
  return _rohc.rohc_compress4(*args)
rohc_compress4 = _rohc.rohc_compress4

def rohc_comp_get_segment2(*args):
  return _rohc.rohc_comp_get_segment2(*args)
rohc_comp_get_segment2 = _rohc.rohc_comp_get_segment2

def rohc_comp_force_contexts_reinit(*args):
  return _rohc.rohc_comp_force_contexts_reinit(*args)
rohc_comp_force_contexts_reinit = _rohc.rohc_comp_force_contexts_reinit

def rohc_comp_profile_enabled(*args):
  return _rohc.rohc_comp_profile_enabled(*args)
rohc_comp_profile_enabled = _rohc.rohc_comp_profile_enabled

def rohc_comp_enable_profile(*args):
  return _rohc.rohc_comp_enable_profile(*args)
rohc_comp_enable_profile = _rohc.rohc_comp_enable_profile

def rohc_comp_disable_profile(*args):
  return _rohc.rohc_comp_disable_profile(*args)
rohc_comp_disable_profile = _rohc.rohc_comp_disable_profile

def rohc_comp_enable_profiles(*args):
  return _rohc.rohc_comp_enable_profiles(*args)
rohc_comp_enable_profiles = _rohc.rohc_comp_enable_profiles

def rohc_comp_disable_profiles(*args):
  return _rohc.rohc_comp_disable_profiles(*args)
rohc_comp_disable_profiles = _rohc.rohc_comp_disable_profiles

def rohc_comp_set_mrru(*args):
  return _rohc.rohc_comp_set_mrru(*args)
rohc_comp_set_mrru = _rohc.rohc_comp_set_mrru

def rohc_comp_get_mrru(*args):
  return _rohc.rohc_comp_get_mrru(*args)
rohc_comp_get_mrru = _rohc.rohc_comp_get_mrru

def rohc_comp_get_max_cid(*args):
  return _rohc.rohc_comp_get_max_cid(*args)
rohc_comp_get_max_cid = _rohc.rohc_comp_get_max_cid

def rohc_comp_get_cid_type(*args):
  return _rohc.rohc_comp_get_cid_type(*args)
rohc_comp_get_cid_type = _rohc.rohc_comp_get_cid_type

def rohc_comp_set_rtp_detection_cb(*args):
  return _rohc.rohc_comp_set_rtp_detection_cb(*args)
rohc_comp_set_rtp_detection_cb = _rohc.rohc_comp_set_rtp_detection_cb

def rohc_comp_set_features(*args):
  return _rohc.rohc_comp_set_features(*args)
rohc_comp_set_features = _rohc.rohc_comp_set_features

def rohc_comp_deliver_feedback2(*args):
  return _rohc.rohc_comp_deliver_feedback2(*args)
rohc_comp_deliver_feedback2 = _rohc.rohc_comp_deliver_feedback2

def rohc_comp_set_wlsb_window_width(*args):
  return _rohc.rohc_comp_set_wlsb_window_width(*args)
rohc_comp_set_wlsb_window_width = _rohc.rohc_comp_set_wlsb_window_width

def rohc_comp_set_periodic_refreshes(*args):
  return _rohc.rohc_comp_set_periodic_refreshes(*args)
rohc_comp_set_periodic_refreshes = _rohc.rohc_comp_set_periodic_refreshes

def rohc_comp_set_list_trans_nr(*args):
  return _rohc.rohc_comp_set_list_trans_nr(*args)
rohc_comp_set_list_trans_nr = _rohc.rohc_comp_set_list_trans_nr

def rohc_comp_get_general_info(*args):
  return _rohc.rohc_comp_get_general_info(*args)
rohc_comp_get_general_info = _rohc.rohc_comp_get_general_info

def rohc_comp_get_last_packet_info2(*args):
  return _rohc.rohc_comp_get_last_packet_info2(*args)
rohc_comp_get_last_packet_info2 = _rohc.rohc_comp_get_last_packet_info2

def rohc_comp_get_state_descr(*args):
  return _rohc.rohc_comp_get_state_descr(*args)
rohc_comp_get_state_descr = _rohc.rohc_comp_get_state_descr
ROHC_DECOMP_STATE_UNKNOWN = _rohc.ROHC_DECOMP_STATE_UNKNOWN
ROHC_DECOMP_STATE_NC = _rohc.ROHC_DECOMP_STATE_NC
ROHC_DECOMP_STATE_SC = _rohc.ROHC_DECOMP_STATE_SC
ROHC_DECOMP_STATE_FC = _rohc.ROHC_DECOMP_STATE_FC
class rohc_decomp_last_packet_info_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, rohc_decomp_last_packet_info_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, rohc_decomp_last_packet_info_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["version_major"] = _rohc.rohc_decomp_last_packet_info_t_version_major_set
    __swig_getmethods__["version_major"] = _rohc.rohc_decomp_last_packet_info_t_version_major_get
    if _newclass:version_major = _swig_property(_rohc.rohc_decomp_last_packet_info_t_version_major_get, _rohc.rohc_decomp_last_packet_info_t_version_major_set)
    __swig_setmethods__["version_minor"] = _rohc.rohc_decomp_last_packet_info_t_version_minor_set
    __swig_getmethods__["version_minor"] = _rohc.rohc_decomp_last_packet_info_t_version_minor_get
    if _newclass:version_minor = _swig_property(_rohc.rohc_decomp_last_packet_info_t_version_minor_get, _rohc.rohc_decomp_last_packet_info_t_version_minor_set)
    __swig_setmethods__["context_mode"] = _rohc.rohc_decomp_last_packet_info_t_context_mode_set
    __swig_getmethods__["context_mode"] = _rohc.rohc_decomp_last_packet_info_t_context_mode_get
    if _newclass:context_mode = _swig_property(_rohc.rohc_decomp_last_packet_info_t_context_mode_get, _rohc.rohc_decomp_last_packet_info_t_context_mode_set)
    __swig_setmethods__["context_state"] = _rohc.rohc_decomp_last_packet_info_t_context_state_set
    __swig_getmethods__["context_state"] = _rohc.rohc_decomp_last_packet_info_t_context_state_get
    if _newclass:context_state = _swig_property(_rohc.rohc_decomp_last_packet_info_t_context_state_get, _rohc.rohc_decomp_last_packet_info_t_context_state_set)
    __swig_setmethods__["profile_id"] = _rohc.rohc_decomp_last_packet_info_t_profile_id_set
    __swig_getmethods__["profile_id"] = _rohc.rohc_decomp_last_packet_info_t_profile_id_get
    if _newclass:profile_id = _swig_property(_rohc.rohc_decomp_last_packet_info_t_profile_id_get, _rohc.rohc_decomp_last_packet_info_t_profile_id_set)
    __swig_setmethods__["nr_lost_packets"] = _rohc.rohc_decomp_last_packet_info_t_nr_lost_packets_set
    __swig_getmethods__["nr_lost_packets"] = _rohc.rohc_decomp_last_packet_info_t_nr_lost_packets_get
    if _newclass:nr_lost_packets = _swig_property(_rohc.rohc_decomp_last_packet_info_t_nr_lost_packets_get, _rohc.rohc_decomp_last_packet_info_t_nr_lost_packets_set)
    __swig_setmethods__["nr_misordered_packets"] = _rohc.rohc_decomp_last_packet_info_t_nr_misordered_packets_set
    __swig_getmethods__["nr_misordered_packets"] = _rohc.rohc_decomp_last_packet_info_t_nr_misordered_packets_get
    if _newclass:nr_misordered_packets = _swig_property(_rohc.rohc_decomp_last_packet_info_t_nr_misordered_packets_get, _rohc.rohc_decomp_last_packet_info_t_nr_misordered_packets_set)
    __swig_setmethods__["is_duplicated"] = _rohc.rohc_decomp_last_packet_info_t_is_duplicated_set
    __swig_getmethods__["is_duplicated"] = _rohc.rohc_decomp_last_packet_info_t_is_duplicated_get
    if _newclass:is_duplicated = _swig_property(_rohc.rohc_decomp_last_packet_info_t_is_duplicated_get, _rohc.rohc_decomp_last_packet_info_t_is_duplicated_set)
    __swig_setmethods__["corrected_crc_failures"] = _rohc.rohc_decomp_last_packet_info_t_corrected_crc_failures_set
    __swig_getmethods__["corrected_crc_failures"] = _rohc.rohc_decomp_last_packet_info_t_corrected_crc_failures_get
    if _newclass:corrected_crc_failures = _swig_property(_rohc.rohc_decomp_last_packet_info_t_corrected_crc_failures_get, _rohc.rohc_decomp_last_packet_info_t_corrected_crc_failures_set)
    __swig_setmethods__["corrected_sn_wraparounds"] = _rohc.rohc_decomp_last_packet_info_t_corrected_sn_wraparounds_set
    __swig_getmethods__["corrected_sn_wraparounds"] = _rohc.rohc_decomp_last_packet_info_t_corrected_sn_wraparounds_get
    if _newclass:corrected_sn_wraparounds = _swig_property(_rohc.rohc_decomp_last_packet_info_t_corrected_sn_wraparounds_get, _rohc.rohc_decomp_last_packet_info_t_corrected_sn_wraparounds_set)
    __swig_setmethods__["corrected_wrong_sn_updates"] = _rohc.rohc_decomp_last_packet_info_t_corrected_wrong_sn_updates_set
    __swig_getmethods__["corrected_wrong_sn_updates"] = _rohc.rohc_decomp_last_packet_info_t_corrected_wrong_sn_updates_get
    if _newclass:corrected_wrong_sn_updates = _swig_property(_rohc.rohc_decomp_last_packet_info_t_corrected_wrong_sn_updates_get, _rohc.rohc_decomp_last_packet_info_t_corrected_wrong_sn_updates_set)
    __swig_setmethods__["packet_type"] = _rohc.rohc_decomp_last_packet_info_t_packet_type_set
    __swig_getmethods__["packet_type"] = _rohc.rohc_decomp_last_packet_info_t_packet_type_get
    if _newclass:packet_type = _swig_property(_rohc.rohc_decomp_last_packet_info_t_packet_type_get, _rohc.rohc_decomp_last_packet_info_t_packet_type_set)
    def __init__(self): 
        this = _rohc.new_rohc_decomp_last_packet_info_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _rohc.delete_rohc_decomp_last_packet_info_t
    __del__ = lambda self : None;
rohc_decomp_last_packet_info_t_swigregister = _rohc.rohc_decomp_last_packet_info_t_swigregister
rohc_decomp_last_packet_info_t_swigregister(rohc_decomp_last_packet_info_t)

class rohc_decomp_general_info_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, rohc_decomp_general_info_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, rohc_decomp_general_info_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["version_major"] = _rohc.rohc_decomp_general_info_t_version_major_set
    __swig_getmethods__["version_major"] = _rohc.rohc_decomp_general_info_t_version_major_get
    if _newclass:version_major = _swig_property(_rohc.rohc_decomp_general_info_t_version_major_get, _rohc.rohc_decomp_general_info_t_version_major_set)
    __swig_setmethods__["version_minor"] = _rohc.rohc_decomp_general_info_t_version_minor_set
    __swig_getmethods__["version_minor"] = _rohc.rohc_decomp_general_info_t_version_minor_get
    if _newclass:version_minor = _swig_property(_rohc.rohc_decomp_general_info_t_version_minor_get, _rohc.rohc_decomp_general_info_t_version_minor_set)
    __swig_setmethods__["contexts_nr"] = _rohc.rohc_decomp_general_info_t_contexts_nr_set
    __swig_getmethods__["contexts_nr"] = _rohc.rohc_decomp_general_info_t_contexts_nr_get
    if _newclass:contexts_nr = _swig_property(_rohc.rohc_decomp_general_info_t_contexts_nr_get, _rohc.rohc_decomp_general_info_t_contexts_nr_set)
    __swig_setmethods__["packets_nr"] = _rohc.rohc_decomp_general_info_t_packets_nr_set
    __swig_getmethods__["packets_nr"] = _rohc.rohc_decomp_general_info_t_packets_nr_get
    if _newclass:packets_nr = _swig_property(_rohc.rohc_decomp_general_info_t_packets_nr_get, _rohc.rohc_decomp_general_info_t_packets_nr_set)
    __swig_setmethods__["comp_bytes_nr"] = _rohc.rohc_decomp_general_info_t_comp_bytes_nr_set
    __swig_getmethods__["comp_bytes_nr"] = _rohc.rohc_decomp_general_info_t_comp_bytes_nr_get
    if _newclass:comp_bytes_nr = _swig_property(_rohc.rohc_decomp_general_info_t_comp_bytes_nr_get, _rohc.rohc_decomp_general_info_t_comp_bytes_nr_set)
    __swig_setmethods__["uncomp_bytes_nr"] = _rohc.rohc_decomp_general_info_t_uncomp_bytes_nr_set
    __swig_getmethods__["uncomp_bytes_nr"] = _rohc.rohc_decomp_general_info_t_uncomp_bytes_nr_get
    if _newclass:uncomp_bytes_nr = _swig_property(_rohc.rohc_decomp_general_info_t_uncomp_bytes_nr_get, _rohc.rohc_decomp_general_info_t_uncomp_bytes_nr_set)
    def __init__(self): 
        this = _rohc.new_rohc_decomp_general_info_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _rohc.delete_rohc_decomp_general_info_t
    __del__ = lambda self : None;
rohc_decomp_general_info_t_swigregister = _rohc.rohc_decomp_general_info_t_swigregister
rohc_decomp_general_info_t_swigregister(rohc_decomp_general_info_t)

ROHC_DECOMP_FEATURE_NONE = _rohc.ROHC_DECOMP_FEATURE_NONE
ROHC_DECOMP_FEATURE_CRC_REPAIR = _rohc.ROHC_DECOMP_FEATURE_CRC_REPAIR
ROHC_DECOMP_FEATURE_COMPAT_1_6_x = _rohc.ROHC_DECOMP_FEATURE_COMPAT_1_6_x

def rohc_decomp_new2(*args):
  return _rohc.rohc_decomp_new2(*args)
rohc_decomp_new2 = _rohc.rohc_decomp_new2

def rohc_decomp_free(*args):
  return _rohc.rohc_decomp_free(*args)
rohc_decomp_free = _rohc.rohc_decomp_free

def rohc_decompress3(*args):
  return _rohc.rohc_decompress3(*args)
rohc_decompress3 = _rohc.rohc_decompress3

def rohc_decomp_get_state_descr(*args):
  return _rohc.rohc_decomp_get_state_descr(*args)
rohc_decomp_get_state_descr = _rohc.rohc_decomp_get_state_descr

def rohc_decomp_get_general_info(*args):
  return _rohc.rohc_decomp_get_general_info(*args)
rohc_decomp_get_general_info = _rohc.rohc_decomp_get_general_info

def rohc_decomp_get_last_packet_info(*args):
  return _rohc.rohc_decomp_get_last_packet_info(*args)
rohc_decomp_get_last_packet_info = _rohc.rohc_decomp_get_last_packet_info

def rohc_decomp_get_cid_type(*args):
  return _rohc.rohc_decomp_get_cid_type(*args)
rohc_decomp_get_cid_type = _rohc.rohc_decomp_get_cid_type

def rohc_decomp_get_max_cid(*args):
  return _rohc.rohc_decomp_get_max_cid(*args)
rohc_decomp_get_max_cid = _rohc.rohc_decomp_get_max_cid

def rohc_decomp_set_mrru(*args):
  return _rohc.rohc_decomp_set_mrru(*args)
rohc_decomp_set_mrru = _rohc.rohc_decomp_set_mrru

def rohc_decomp_get_mrru(*args):
  return _rohc.rohc_decomp_get_mrru(*args)
rohc_decomp_get_mrru = _rohc.rohc_decomp_get_mrru

def rohc_decomp_set_prtt(*args):
  return _rohc.rohc_decomp_set_prtt(*args)
rohc_decomp_set_prtt = _rohc.rohc_decomp_set_prtt

def rohc_decomp_get_prtt(*args):
  return _rohc.rohc_decomp_get_prtt(*args)
rohc_decomp_get_prtt = _rohc.rohc_decomp_get_prtt

def rohc_decomp_set_rate_limits(*args):
  return _rohc.rohc_decomp_set_rate_limits(*args)
rohc_decomp_set_rate_limits = _rohc.rohc_decomp_set_rate_limits

def rohc_decomp_get_rate_limits(*args):
  return _rohc.rohc_decomp_get_rate_limits(*args)
rohc_decomp_get_rate_limits = _rohc.rohc_decomp_get_rate_limits

def rohc_decomp_set_features(*args):
  return _rohc.rohc_decomp_set_features(*args)
rohc_decomp_set_features = _rohc.rohc_decomp_set_features

def rohc_decomp_profile_enabled(*args):
  return _rohc.rohc_decomp_profile_enabled(*args)
rohc_decomp_profile_enabled = _rohc.rohc_decomp_profile_enabled

def rohc_decomp_enable_profile(*args):
  return _rohc.rohc_decomp_enable_profile(*args)
rohc_decomp_enable_profile = _rohc.rohc_decomp_enable_profile

def rohc_decomp_disable_profile(*args):
  return _rohc.rohc_decomp_disable_profile(*args)
rohc_decomp_disable_profile = _rohc.rohc_decomp_disable_profile

def rohc_decomp_enable_profiles(*args):
  return _rohc.rohc_decomp_enable_profiles(*args)
rohc_decomp_enable_profiles = _rohc.rohc_decomp_enable_profiles

def rohc_decomp_disable_profiles(*args):
  return _rohc.rohc_decomp_disable_profiles(*args)
rohc_decomp_disable_profiles = _rohc.rohc_decomp_disable_profiles

def rohc_decomp_set_traces_cb2(*args):
  return _rohc.rohc_decomp_set_traces_cb2(*args)
rohc_decomp_set_traces_cb2 = _rohc.rohc_decomp_set_traces_cb2
print_rohc_traces = _rohc.print_rohc_traces
gen_false_random_num = _rohc.gen_false_random_num
rohc_comp_rtp_cb = _rohc.rohc_comp_rtp_cb
# This file is compatible with both classic and new-style classes.


